// The pool of board icons a card can pick from (bingo_tasks.tile_icon).
// Every key must exist in ICONS in components/BingoTileFace.tsx. A card with no
// pick (null) takes the icon of its category instead.

export const TILE_ICON_POOL: ReadonlyArray<{ key: string; label: string }> = [
  { key: 'target', label: 'Target' },
  { key: 'trophy', label: 'Trophy' },
  { key: 'star', label: 'Star' },
  { key: 'flag', label: 'Flag' },
  { key: 'zap', label: 'Lightning' },
  { key: 'activity', label: 'Activity' },
  { key: 'users', label: 'Team' },
  { key: 'hand', label: 'Hand' },
  { key: 'knot', label: 'Linked' },
  { key: 'kart', label: 'Car' },
  { key: 'parcel', label: 'Parcel' },
  { key: 'cup', label: 'Cup' },
  { key: 'shoe', label: 'Shoe' },
  { key: 'caterpillar', label: 'Caterpillar' },
  { key: 'bottle', label: 'Bottle' },
  { key: 'ring', label: 'Ring toss' },
  { key: 'jenga', label: 'Blocks' },
  { key: 'tictactoe', label: 'Tic tac toe' },
  { key: 'chair', label: 'Chair' },
  { key: 'cube', label: 'Cube' },
  { key: 'puzzle', label: 'Puzzle' },
  { key: 'flip', label: 'Flip panels' },
  { key: 'cards', label: 'Cards' },
  { key: 'beans', label: 'Beans' },
  { key: 'spot', label: 'Spot it' },
  { key: 'search', label: 'Search' },
  { key: 'lightbulb', label: 'Idea' },
  { key: 'book', label: 'Book' },
  { key: 'quiz', label: 'Question' },
  { key: 'lock', label: 'Lock' },
  { key: 'math', label: 'Maths' },
  { key: 'cpu', label: 'Tech' },
  { key: 'sparkles', label: 'Sparkles' },
  { key: 'music', label: 'Music' },
  { key: 'camera', label: 'Camera' },
  { key: 'message', label: 'Chat' },
  { key: 'compass', label: 'Compass' },
  { key: 'bag', label: 'Bag' },
]
