-- aitb_pool_items: word/photo pools for AI Team Building's interactive
-- modules (Nerf cups' Character/Action/Scene, roulette's Genre/Topic, the
-- card deal's Country/Character/Scene/Style), admin-editable instead of
-- hardcoded in src/lib/aitbActivities.ts. A single shared house dataset —
-- not per-tenant data, same permissive RLS as the rest of AITB.
-- Source: aitb/018_aitb_pool_items.sql.

create table public.aitb_pool_items (
  id         uuid primary key default gen_random_uuid(),
  pool_key   text not null,
  label      text not null,
  photo_url  text,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create index aitb_pool_items_pool_idx on public.aitb_pool_items (pool_key, sort_order);

alter table public.aitb_pool_items enable row level security;
create policy "anon rw aitb_pool_items" on public.aitb_pool_items for all using (true) with check (true);

alter publication supabase_realtime add table public.aitb_pool_items;

-- Seed: every word/photo currently hardcoded. Rows with real reel art
-- (genre/topic/country/cardChar/cardScene/style) keep that as their
-- starting photo_url; the cup pools (cupCharacter/cupAction/cupScene)
-- start with no photo since no art exists for those.
insert into public.aitb_pool_items (id, pool_key, label, photo_url, sort_order) values
  (gen_random_uuid(), 'cupCharacter', 'A grumpy astronaut', null, 0),
  (gen_random_uuid(), 'cupCharacter', 'A disco unicorn', null, 1),
  (gen_random_uuid(), 'cupCharacter', 'A samurai chef', null, 2),
  (gen_random_uuid(), 'cupCharacter', 'A robot grandma', null, 3),
  (gen_random_uuid(), 'cupCharacter', 'A ninja penguin', null, 4),
  (gen_random_uuid(), 'cupCharacter', 'A wizard toddler', null, 5),
  (gen_random_uuid(), 'cupCharacter', 'A pirate librarian', null, 6),
  (gen_random_uuid(), 'cupCharacter', 'A cyborg cat', null, 7),
  (gen_random_uuid(), 'cupCharacter', 'A viking ballerina', null, 8),
  (gen_random_uuid(), 'cupCharacter', 'A detective sloth', null, 9),
  (gen_random_uuid(), 'cupCharacter', 'A superhero janitor', null, 10),
  (gen_random_uuid(), 'cupCharacter', 'A vampire barista', null, 11),
  (gen_random_uuid(), 'cupAction', 'riding a rocket', null, 0),
  (gen_random_uuid(), 'cupAction', 'breakdancing', null, 1),
  (gen_random_uuid(), 'cupAction', 'brewing potions', null, 2),
  (gen_random_uuid(), 'cupAction', 'surfing on lava', null, 3),
  (gen_random_uuid(), 'cupAction', 'juggling planets', null, 4),
  (gen_random_uuid(), 'cupAction', 'escaping a maze', null, 5),
  (gen_random_uuid(), 'cupAction', 'taming a dragon', null, 6),
  (gen_random_uuid(), 'cupAction', 'stealing a giant cookie', null, 7),
  (gen_random_uuid(), 'cupAction', 'arm-wrestling a bear', null, 8),
  (gen_random_uuid(), 'cupAction', 'painting the sky', null, 9),
  (gen_random_uuid(), 'cupAction', 'deep-sea diving', null, 10),
  (gen_random_uuid(), 'cupAction', 'racing a cheetah', null, 11),
  (gen_random_uuid(), 'cupScene', 'in a neon jungle', null, 0),
  (gen_random_uuid(), 'cupScene', 'on the moon', null, 1),
  (gen_random_uuid(), 'cupScene', 'inside a volcano', null, 2),
  (gen_random_uuid(), 'cupScene', 'in a candy kingdom', null, 3),
  (gen_random_uuid(), 'cupScene', 'in an underwater city', null, 4),
  (gen_random_uuid(), 'cupScene', 'in a haunted mansion', null, 5),
  (gen_random_uuid(), 'cupScene', 'atop a skyscraper', null, 6),
  (gen_random_uuid(), 'cupScene', 'in a desert oasis', null, 7),
  (gen_random_uuid(), 'cupScene', 'in a cyberpunk market', null, 8),
  (gen_random_uuid(), 'cupScene', 'in an ancient temple', null, 9),
  (gen_random_uuid(), 'cupScene', 'on a floating island', null, 10),
  (gen_random_uuid(), 'cupScene', 'in a frozen tundra', null, 11),
  (gen_random_uuid(), 'genre', '70s Disco', '/aitb/reels/genre/70s-disco.webp', 0),
  (gen_random_uuid(), 'genre', 'Acoustic Café', '/aitb/reels/genre/acoustic-caf.webp', 1),
  (gen_random_uuid(), 'genre', 'Bollywood', '/aitb/reels/genre/bollywood.webp', 2),
  (gen_random_uuid(), 'genre', 'Broadway Musical', '/aitb/reels/genre/broadway-musical.webp', 3),
  (gen_random_uuid(), 'genre', 'Country Ballad', '/aitb/reels/genre/country-ballad.webp', 4),
  (gen_random_uuid(), 'genre', 'Dangdut', '/aitb/reels/genre/dangdut.webp', 5),
  (gen_random_uuid(), 'genre', 'EDM Anthem', '/aitb/reels/genre/edm-anthem.webp', 6),
  (gen_random_uuid(), 'genre', 'Hip-Hop', '/aitb/reels/genre/hip-hop.webp', 7),
  (gen_random_uuid(), 'genre', 'Joget', '/aitb/reels/genre/joget.webp', 8),
  (gen_random_uuid(), 'genre', 'K-Pop', '/aitb/reels/genre/k-pop.webp', 9),
  (gen_random_uuid(), 'genre', 'Lo-fi Chill', '/aitb/reels/genre/lo-fi-chill.webp', 10),
  (gen_random_uuid(), 'genre', 'Nursery Rhyme', '/aitb/reels/genre/nursery-rhyme.webp', 11),
  (gen_random_uuid(), 'genre', 'Opera', '/aitb/reels/genre/opera.webp', 12),
  (gen_random_uuid(), 'genre', 'Reggae', '/aitb/reels/genre/reggae.webp', 13),
  (gen_random_uuid(), 'genre', 'Smooth Jazz', '/aitb/reels/genre/smooth-jazz.webp', 14),
  (gen_random_uuid(), 'topic', 'Annual Leave', '/aitb/reels/topic/annual-leave.webp', 0),
  (gen_random_uuid(), 'topic', 'Endless Zoom Calls', '/aitb/reels/topic/endless-zoom-calls.webp', 1),
  (gen_random_uuid(), 'topic', 'Impossible Deadlines', '/aitb/reels/topic/impossible-deadlines.webp', 2),
  (gen_random_uuid(), 'topic', 'KPI Targets', '/aitb/reels/topic/kpi-targets.webp', 3),
  (gen_random_uuid(), 'topic', 'Monday Mornings', '/aitb/reels/topic/monday-mornings.webp', 4),
  (gen_random_uuid(), 'topic', 'Nasi Lemak', '/aitb/reels/topic/nasi-lemak.webp', 5),
  (gen_random_uuid(), 'topic', 'Teh Tarik', '/aitb/reels/topic/teh-tarik.webp', 6),
  (gen_random_uuid(), 'topic', 'The Boss', '/aitb/reels/topic/the-boss.webp', 7),
  (gen_random_uuid(), 'topic', 'The Broken Printer', '/aitb/reels/topic/the-broken-printer.webp', 8),
  (gen_random_uuid(), 'topic', 'The Company Canteen', '/aitb/reels/topic/the-company-canteen.webp', 9),
  (gen_random_uuid(), 'topic', 'The Office Coffee', '/aitb/reels/topic/the-office-coffee.webp', 10),
  (gen_random_uuid(), 'topic', 'The Team WhatsApp Group', '/aitb/reels/topic/the-team-whatsapp-group.webp', 11),
  (gen_random_uuid(), 'topic', 'Traffic Jams', '/aitb/reels/topic/traffic-jams.webp', 12),
  (gen_random_uuid(), 'topic', 'Working Overtime', '/aitb/reels/topic/working-overtime.webp', 13),
  (gen_random_uuid(), 'country', 'Ancient Egypt', '/aitb/reels/country/ancient-egypt.webp', 0),
  (gen_random_uuid(), 'country', 'Ancient Greece', '/aitb/reels/country/ancient-greece.webp', 1),
  (gen_random_uuid(), 'country', 'Babylon', '/aitb/reels/country/babylon.webp', 2),
  (gen_random_uuid(), 'country', 'Feudal Japan', '/aitb/reels/country/feudal-japan.webp', 3),
  (gen_random_uuid(), 'country', 'Ming Dynasty China', '/aitb/reels/country/ming-dynasty-china.webp', 4),
  (gen_random_uuid(), 'country', 'Mughal India', '/aitb/reels/country/mughal-india.webp', 5),
  (gen_random_uuid(), 'country', 'The Aztec Empire', '/aitb/reels/country/the-aztec-empire.webp', 6),
  (gen_random_uuid(), 'country', 'The Inca Empire', '/aitb/reels/country/the-inca-empire.webp', 7),
  (gen_random_uuid(), 'country', 'The Mali Empire', '/aitb/reels/country/the-mali-empire.webp', 8),
  (gen_random_uuid(), 'country', 'The Ottoman Empire', '/aitb/reels/country/the-ottoman-empire.webp', 9),
  (gen_random_uuid(), 'country', 'The Roman Empire', '/aitb/reels/country/the-roman-empire.webp', 10),
  (gen_random_uuid(), 'country', 'Viking Norse', '/aitb/reels/country/viking-norse.webp', 11),
  (gen_random_uuid(), 'cardChar', 'A Blind Prophet', '/aitb/reels/cardChar/a-blind-prophet.webp', 0),
  (gen_random_uuid(), 'cardChar', 'A Court Jester', '/aitb/reels/cardChar/a-court-jester.webp', 1),
  (gen_random_uuid(), 'cardChar', 'A Fallen Knight', '/aitb/reels/cardChar/a-fallen-knight.webp', 2),
  (gen_random_uuid(), 'cardChar', 'A High Priestess', '/aitb/reels/cardChar/a-high-priestess.webp', 3),
  (gen_random_uuid(), 'cardChar', 'A Masked Assassin', '/aitb/reels/cardChar/a-masked-assassin.webp', 4),
  (gen_random_uuid(), 'cardChar', 'A Pirate Captain', '/aitb/reels/cardChar/a-pirate-captain.webp', 5),
  (gen_random_uuid(), 'cardChar', 'A Rogue General', '/aitb/reels/cardChar/a-rogue-general.webp', 6),
  (gen_random_uuid(), 'cardChar', 'A Street Orphan', '/aitb/reels/cardChar/a-street-orphan.webp', 7),
  (gen_random_uuid(), 'cardChar', 'A Wandering Monk', '/aitb/reels/cardChar/a-wandering-monk.webp', 8),
  (gen_random_uuid(), 'cardChar', 'A Warrior Queen', '/aitb/reels/cardChar/a-warrior-queen.webp', 9),
  (gen_random_uuid(), 'cardChar', 'A Young Blacksmith', '/aitb/reels/cardChar/a-young-blacksmith.webp', 10),
  (gen_random_uuid(), 'cardChar', 'An Exiled Prince', '/aitb/reels/cardChar/an-exiled-prince.webp', 11),
  (gen_random_uuid(), 'cardScene', 'A Burning City', '/aitb/reels/cardScene/a-burning-city.webp', 0),
  (gen_random_uuid(), 'cardScene', 'A Crowded Market Chase', '/aitb/reels/cardScene/a-crowded-market-chase.webp', 1),
  (gen_random_uuid(), 'cardScene', 'A Desert Ambush', '/aitb/reels/cardScene/a-desert-ambush.webp', 2),
  (gen_random_uuid(), 'cardScene', 'A Duel at Dawn', '/aitb/reels/cardScene/a-duel-at-dawn.webp', 3),
  (gen_random_uuid(), 'cardScene', 'A Frozen Mountain Pass', '/aitb/reels/cardScene/a-frozen-mountain-pass.webp', 4),
  (gen_random_uuid(), 'cardScene', 'A Grand Feast Betrayal', '/aitb/reels/cardScene/a-grand-feast-betrayal.webp', 5),
  (gen_random_uuid(), 'cardScene', 'A Royal Coronation', '/aitb/reels/cardScene/a-royal-coronation.webp', 6),
  (gen_random_uuid(), 'cardScene', 'A Sacred Temple Ritual', '/aitb/reels/cardScene/a-sacred-temple-ritual.webp', 7),
  (gen_random_uuid(), 'cardScene', 'A Secret Tunnel Escape', '/aitb/reels/cardScene/a-secret-tunnel-escape.webp', 8),
  (gen_random_uuid(), 'cardScene', 'A Stormy Sea Battle', '/aitb/reels/cardScene/a-stormy-sea-battle.webp', 9),
  (gen_random_uuid(), 'style', 'Cartoon Animated', '/aitb/reels/style/cartoon-animated.webp', 0),
  (gen_random_uuid(), 'style', 'Horror Movie', '/aitb/reels/style/horror-movie.webp', 1),
  (gen_random_uuid(), 'style', 'Old School Black & White', '/aitb/reels/style/old-school-black-white.webp', 2),
  (gen_random_uuid(), 'style', 'Slow-Motion Epic', '/aitb/reels/style/slow-motion-epic.webp', 3);
