import { useEffect, useRef, useCallback } from 'react'
import { supabase, isSupabaseConfigured } from '../lib/supabase'

// ════════════════════════════════════════════════════════════════════════════
// SAMPLE REMOTE — pairs two devices for the Bingo Dash demo over an ephemeral
// Supabase broadcast channel (no DB writes, so the sandbox stays clean).
//
//  • Projector (device 1): applies incoming `command`s and broadcasts its full
//    `state` snapshot on every change so the controller mirrors what's on screen.
//  • Controller (device 2): sends `command`s and reflects the projector's `state`.
//
// Both join `sample-remote-<code>`; the code is generated by the projector and
// carried to the controller via the pairing QR / link (?remote=<code>).
// ════════════════════════════════════════════════════════════════════════════

export type RemoteCommand =
  | { action: 'selectBoard'; id: string }
  | { action: 'join'; teamName: string }
  | { action: 'leave' }
  | { action: 'openTask'; taskId: string }
  | { action: 'closeTask' }
  | { action: 'complete'; taskId: string }
  | { action: 'uncomplete'; taskId: string }
  | { action: 'quickWin' }
  | { action: 'reset' }
  | { action: 'setView'; view: SampleView }
  // Task-detail flow (drive the open tile's screens from the phone)
  | { action: 'startChallenge' }
  | { action: 'nextPage' }
  | { action: 'prevPage' }
  | { action: 'fillMarshal' }
  | { action: 'submitComplete' }
  | { action: 'scroll'; direction: 'up' | 'down' } // scroll the projector's viewport
  // The BINGO celebration covering the projector. It self-clears after 4s, so
  // dismiss is about skipping ahead when several lines land at once.
  | { action: 'dismissPopup' }
  // Open or close the help-chat message box on the projector.
  | { action: 'setChat'; open: boolean }
  // Put the Invite-teammate QR on the projector, or take it away.
  | { action: 'setInvite'; open: boolean }
  | { action: 'requestState' } // controller → projector: "resend your state now"

export type SampleView = 'board' | 'scoreboard'

// Live step of the open task detail, so the controller shows the right buttons.
export type DetailStep = {
  phase: 'splash' | 'main'
  pageIndex: number
  pageCount: number
  isMarshalTask: boolean
  marshalFilled: boolean
}

export type RemoteState = {
  selectedId: string | null
  teamName: string | null
  scanState: Record<string, 'scanned' | 'completed'>
  openTaskId: string | null
  view: SampleView
  detail: DetailStep | null
  /**
   * The BINGO celebration on screen right now ('B', 'BI', … 'BINGO'), or null.
   * Full-screen and opaque, so the controller has to know: without this the
   * phone offers board controls while the room sees only the celebration, and
   * taps look ignored even though they apply underneath.
   */
  popup: string | null
  /** Celebrations still queued behind this one — one per line just completed. */
  popupQueued: number
  /** Whether the Invite-teammate QR overlay is up on the projector. */
  inviteOpen: boolean
  /** Bingo lines Quick BINGO has completed so far, 0-5 — one per press. */
  quickWinRows: number
  /** Whether the help-chat message box is open on the projector. */
  chatOpen: boolean
}

/**
 * How often the projector re-broadcasts its state, and how long the phone
 * waits before calling the link dead. The gap is deliberately ~3 beats: one
 * dropped broadcast on venue Wi-Fi should not flip the phone to
 * "Reconnecting" mid-sentence.
 */
export const HEARTBEAT_MS = 3000
export const HEARTBEAT_TIMEOUT_MS = 10000

/** Short, unambiguous pairing code (no 0/O/1/I to avoid QR-less typos). */
export function makeRemoteCode(): string {
  const alphabet = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'
  let out = ''
  for (let i = 0; i < 5; i++) out += alphabet[Math.floor(Math.random() * alphabet.length)]
  return out
}

export function useSampleRemote(
  code: string | null,
  handlers: { onCommand?: (c: RemoteCommand) => void; onState?: (s: RemoteState) => void },
) {
  // Keep the latest handlers without re-subscribing the channel on every render.
  const ref = useRef(handlers)
  ref.current = handlers
  const channelRef = useRef<ReturnType<typeof supabase.channel> | null>(null)

  useEffect(() => {
    if (!code || !isSupabaseConfigured) return
    const channel = supabase.channel(`sample-remote-${code}`, { config: { broadcast: { self: false } } })
    channel.on('broadcast', { event: 'command' }, ({ payload }) => ref.current.onCommand?.(payload as RemoteCommand))
    channel.on('broadcast', { event: 'state' }, ({ payload }) => ref.current.onState?.(payload as RemoteState))
    channel.subscribe()
    channelRef.current = channel
    return () => { supabase.removeChannel(channel); channelRef.current = null }
  }, [code])

  const sendCommand = useCallback((c: RemoteCommand) => {
    channelRef.current?.send({ type: 'broadcast', event: 'command', payload: c })
  }, [])
  const sendState = useCallback((s: RemoteState) => {
    channelRef.current?.send({ type: 'broadcast', event: 'state', payload: s })
  }, [])

  return { sendCommand, sendState }
}
